<?php

function biblio_record_node_info() {
	return array(
		'biblio_record' => array(
			'name' => t('Drupac Biblio Record'),
			'base' => 'biblio_record',
			'description' => t('Allows you import biblio data'),
			'has_title' => TRUE,
			'title_label' => t('Title'),
		)
	);
}

function biblio_record_form($node, &$form_state) {
	$type = node_type_get_type($node);

	$form['title'] = array(
		'#type' => 'textfield',
		'#title' => check_plain($type->title_label),
		'#default_value' => !empty($node->title) ? $node->title : '',
		'#required' => true,
	);

	return $form;
}
