<?php

function harvest_import_record($id) {
    $record = sigb_connector_scrape_bib($id);
    
    $node = new stdClass();
    $node->type = 'biblio_record';
    node_object_prepare($node);
    $node->title = $record['title'];
    unset( $record['title'] );

    foreach ( $record as $name => $values ) {
	if ( is_array( $values ) ) {
	    foreach ( $values as $value ) {
	        $node->{$name}['und'][] = array( 'value' => $value );
	    }
	}
	else {
	    $node->{$name}['und'][0]['value'] = $values;
	}
    }
    
    $node = node_submit($node);
    node_save($node);
    return $node->nid;
}

function harvest_import_records($offset, $number) {
    $count = 0;
    for ( $i = $offset; $i < $offset+$number; $i++ ) {
	echo $count++ %10 ? "$i " : "$i ** $count done.\n";
        harvest_import_record($i);
    }
}
